services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    command: npm run dev -- -p 3000 -H 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
      - web_next:/app/.next
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  web_node_modules:
  web_next: