# k8s/app/web.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: streemm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: node:20-alpine
        command:
        - sh
        - -c
        - |
          cd /app
          npm ci
          npm run dev -- -p 3000 -H 0.0.0.0
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: streemm-config
        volumeMounts:
        - name: web-code
          mountPath: /app
        - name: node-modules
          mountPath: /app/node_modules
        - name: next-cache
          mountPath: /app/.next
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 12 # 2 minute window
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: web-code
        hostPath:
          path: /streemm/apps/web
          type: Directory
      - name: node-modules
        emptyDir: {}
      - name: next-cache
        emptyDir: {}

---
# ClusterIP service for internal SSR requests
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: streemm
spec:
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 3000
    name: http

---
# NodePort service for browser access (localhost:3000)
apiVersion: v1
kind: Service
metadata:
  name: web-external
  namespace: streemm
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    name: http
