# k8s/stateful/minio.yaml

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: streem
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-09-22T00-33-43Z
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        - name: MINIO_API_CORS_ALLOW_ORIGIN
          value: "http://localhost:3000,http://127.0.0.1:3000"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /root/.minio
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi

---
# Headless service for internal cluster access
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: streem
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: api
  - port: 9001
    targetPort: 9001
    name: console

---
# NodePort service for S3 API external access
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: streem
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30002
    name: api

---
# NodePort service for web console external access
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: streem
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9001
    targetPort: 9001
    nodePort: 30003
    name: console
